In [68]:
import numpy as np
input = """30373
25512
65332
33549
35390"""

input = input.splitlines()

x = np.array([list(map(int,x)) for x in input]); x

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [123]:
import numpy as np
input = open("input.txt", "r").read()
input = input.splitlines()

x = np.array([list(map(int,x)) for x in input]); x

array([[4, 2, 2, ..., 1, 2, 1],
       [3, 0, 1, ..., 1, 3, 4],
       [4, 1, 0, ..., 3, 4, 3],
       ...,
       [3, 3, 2, ..., 2, 3, 1],
       [1, 1, 0, ..., 1, 3, 1],
       [2, 3, 1, ..., 1, 1, 4]])

In [3]:
len(x), len(x[0])

(5, 5)

In [26]:
x[:1]

[[3, 0, 3, 7, 3]]

In [57]:
res = 0
M,N = len(x), len(x[0]), 
for r in range(1, M-1):
    for c in range(1, N-1):
        # left
        curr = x[r][c]
        l = sorted(x[r][:c], reverse=True)
        if curr > l[0]:
            res += 1
            continue
        
        # right
        curr = x[r][c]
        ri = sorted(x[r][c+1:], reverse=True)
        if curr > ri[0]:
            res += 1
            continue

        # up
        curr = x[r][c]
        u = sorted(x[:,c][:r], reverse=True)
        if curr > u[0]:
            res += 1
            continue

        # down
        curr = x[r][c]
        d = sorted(x[:,c][r+1:], reverse=True)
        if curr > d[0]:
            res += 1
            continue

In [126]:
res = 0
M,N = len(x), len(x[0])

def f(x, s):
    i = 0
    while i < len(x) and curr > x[i]: i+=1
    s *= len(x[:i+1])
    return s
for r in range(1, M-1):
    for c in range(1, N-1):
        s = 1
        curr = x[r][c]

        # left
        xx = x[r][:c][::-1]
        s = f(xx, s)
        
        # right
        xx = x[r][c+1:]
        s = f(xx, s)

        # up
        xx = x[:,c][:r][::-1]
        s = f(xx, s)

        # downs
        xx = x[:,c][r+1:]
        s = f(xx, s)

        if s > res: res = s
res

595080

In [84]:
res

5

In [121]:
print(np.flip(np.array([1,2,3,4])))

np.array([1,2,3,4])[::-1]

[4 3 2 1]


array([4, 3, 2, 1])

In [58]:
res + 2*M + 2*N - 4

1543